web:
    image: wordpress
    volumes:
        - ./src/:/var/www/html/
    links:
        - db
    # For Apache based image:
    ports:
        - "9010:80"
db:
    image: mysql:8.0
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: myreallyhardpass1337
        MYSQL_DATABASE: beton
        MYSQL_USER: beton
        MYSQL_PASSWORD: betonpass
